[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Paper Review"
  pageRef = "reviews"
  weight = 30

[[main]]
  name = "Coursework"
  pageRef = "coursework"
  weight = 40
